Fix spm bundle
chausovSurfStudio/SurfPlaybook pull request #13
Opened 2023-01-20 11:12 UTC by dmitry2101

# What is done

- Пофикшен баг неправильного определения Bundle у ячейки

2023-01-23 10:56 UTC, chausovSurfStudio requested changes
да, а мне соответственно надо пойти и поправить CI((

2023-01-23 10:56 UTC, chausovSurfStudio commented on SurfPlaybook/Library/Protocols/CellConfigurable.swift
> +public protocol CellConfigurable {
переложи его в Playbook/Core/Protocols, а то публичные вещи именно там лежат, а здесь - больше внутренние)

2023-01-23 12:41 UTC, dmitry2101 commented on SurfPlaybook/Library/Protocols/CellConfigurable.swift
> +public protocol CellConfigurable {
done

2023-01-23 12:45 UTC, chausovSurfStudio approved these changes, later dismissed

2023-01-24 06:59 UTC, Alelenka approved these changes

2023-01-24 07:40 UTC, chausovSurfStudio approved these changes

2023-01-24 07:41 UTC, merged